### PR TITLE
increase resource limits

### PR DESCRIPTION
**Pull request by 27149chen**

### CODE REVIEW

**Comment by shay-berman** [comment]
@27149chen 
1. I review k8s documentation and it looks like the default mem request=256 and limit=512Mi.
So why you choose request=40 and limit=400?

2. also about cpu, the default cpu request=0.5 and cpu limit=750m.
So why you choose smaller limit?

**Comment by 27149chen** [comment]
> @27149chen
> 
>     1. I review k8s documentation and it looks like the default mem request=256 and limit=512Mi.
>        So why you choose request=40 and limit=400?
> 
>     2. also about cpu, the default cpu request=0.5 and cpu limit=750m.
>        So why you choose smaller limit?

can you show me the doc?

**Comment by shay-berman** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

**Comment by shay-berman** [comment]
ok, you mentioned tests pass ok,
so please wait for staging to complete then merge the PR (will be RC2)
Then run the CI CSI_XAVI_Production_CI_Trigger so it will run with the latest operator build.

**Comment by oriyarde** [comment]
@27149chen could we delete this branch?

**Pull request closed without merging**
